# -*- coding: utf-8 -*-
"""apphelloworld.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12p0CPP8NnVEivmBTqcTPE94ydFqsWt9C
"""

import streamlit as st

st.title("Hello World")
st.write("Ini adalah aplikasi Streamlit pertama saya!")


